FROM ocaml/opam2:4.05


RUN sudo apt update\
&& sudo apt install curl -y\
&& sudo apt install m4 -y\
&& opam pin add coq 8.6\
&& eval $(opam env)\
&& cd ..\
&& git clone -b jscoq https://github.com/atlanmod/CoqTL.git\
&& cd CoqTL\
&& make
